spec-version: 0.36.0

name: GHCIInterface
synopsis: Interface module between GHCi and TeXmacs
github: CubOfJudahsLion/tm-ghci
version: 0.2.1.0
author: Alexander Feterman Naranjo <10951848+CubOfJudahsLion@users.noreply.github.com>
copyright: (c) 2023-2026 Alexander Feterman Naranjo
license: GPL-3.0-or-later
category:
  - Control
  - Language
  - Text
tested-with: GHC == 9.10.3

dependencies:
  - base >= 4.19.1 && < 5

language: GHC2021

executable:
  source-dirs: src
  main: Main.hs
  dependencies:
    - deepseq
    - process
  other-extensions:
    - DeriveAnyClass
    - PatternSynonyms
    - StandaloneDeriving
    - TypeData
    - TypeFamilies

tests:
  test:
    source-dirs: tests
    main: Main.hs
    dependencies:
      - hspec
      - quicktest
      - tasty

